### ISSUE TITLE
4월 7주차 - 클라이언트 과제

### ISSUE THREAD

**Issue by C17AN** [GME-392/sanhak-client#26]
### 찬민
- 회원가입 시, 비밀번호와 비밀번호 재확인 입력이 같아야만 버튼을 클릭할 수 있도록 수정할것 [✅] = 작업완료
- 비밀번호를 DB에 전송 시, sha256 등으로 해쉬화된 값을 보내도록 수정할것 [❌]
    - 보류, 비밀번호 변경 기능을 어떻게 구현해야할지 정한 이후
- 마이페이지 만들것 [진행중]
![image](https://user-images.githubusercontent.com/26535030/114494669-b5bbbe80-9c57-11eb-91e0-8549ce87d0c4.png)

- 그룹 페이지 초안 만들것 [진행중]
![image](https://user-images.githubusercontent.com/26535030/114494705-c53b0780-9c57-11eb-96d6-6ae2e4650dd6.png)

---

4월 14일 과제 추가
- 로그인 실패시 붉은 텍스트로 "로그인에 실패하였습니다" 넣기 (가능하면 실패 사유까지 (Ex. 비밀번호가 일치하지 않습니다)

**Comment by C17AN** [comment]
@jane-k @SongGol @suhwan-cheon @kimtaehyun98 
혹시 저희 작업목표 / 작업내용을 이렇게 주간 이슈로도 관리하는건 어떨까요?
다른 분들이 진행하고 있는 내용을 파악하기 더 쉬울 듯 해서요 😄

**Comment by suhwan-cheon** [comment]
### 수환

- 회원가입 시, 이메일 인증 코드 페이지 테마 맞게 수정하기 []
- 아이디/비밀번호 찾기 구현하기 (cognito - forgotpassword) []
- 소속 그룹 목록 표시하기 []

**Comment by kimtaehyun98** [comment]
### **태현**

- 랭킹 기능 관련 정보들을 DB로부터 받아와 랭킹 값을 반환하는 Lambda 함수 구현하기 []
- 개인별 분석 보고서 메일링 기능 AWS SES로 구현하기 []
- 문제 추천 시스템 구현하기 []
